spring:
  data:
    mongodb:
      uri: ${ITEM_DB_HOST:mongodb://localhost:27071/item}
  kafka:
    topic: "item-created-event"
    cancelordertopic: "cancelorder"
    ordercreatedtopic: "orderevent"
    ordereventconsumer:
      group-id: order-service-listeners
    ordercancelconsumer:
      group-id: order-cancel-listeners
    orderexpiredconsumer:
      group-id: order-expired-item-consumers
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties[request.timeout.ms]: 600000
    admin:
      properties:
        bootstrap-servers: kafka-service:9092
    bootstrap-servers: kafka-service:9092

server:
  port: 8082

