spring:
  data:
    mongodb:
      uri: ${ITEM_DB_HOST:mongodb://localhost:27071/item}
  kafka:
    topic: "item-created-event"
    cancelordertopic: "cancelorder"
    ordercreatedtopic: "orderevent"
    itemserviceconsumer:
      group-id: item-service-listeners
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties[request.timeout.ms]: 600000
    admin:
      properties:
        bootstrap-servers: kafka-service:9092
    bootstrap-servers: kafka-service:9092

server:
  port: 8082

